### PR TITLE
CONTRAST-21811 Jenkins - set a flag in Jenkins to use or disregard Co…

### PR DESCRIPTION
**Pull request by serge17**
Now, the user can choose to ignore app vulnerabilities by adding a "ignoreContrastFindings" boolean build parameter to the Jenkins job.

https://wiki.jenkins.io/display/JENKINS/Parameterized+Build

### CODE REVIEW

**Comment by gmoore** [comment]
@serge17 Where does one set ignoreContrastFindings ?

**Comment by serge17** [comment]
@gmoore Like this:

untitled

**Comment by gmoore** [comment]
Thanks. Can you add this **and any other params we've added since 2.1** to the top of the README and the Jenkins/Contrast wiki page.

Also: Add a column for "since" to indicate which version the params were added. 

Thanks!

**Comment by serge17** [comment]
@gmoore Done, files are updated.

**Comment by gmoore** [comment]
Did this issue introduce any new variables?

**Comment by serge17** [comment]
@gmoore Just the optional build parameter ignoreContrastFindings

**Comment by gmoore** [comment]
Commented on the wrong PR. I meant this one: https://github.com/jenkinsci/contrast-continuous-application-security-plugin/pull/14

**Pull request merged**
