### PR TITLE
CONTRAST-21810

### PR DESCRIPTION
**Pull request by serge17**
Added drop-down option "Result of a vulnerable build" to TeamServer profile configuration.

### CODE REVIEW

**Comment by gmoore** [comment]
@serge17 Getting some test failures here after merging in develop. Can you look?

**Comment by serge17** [comment]
@gmoore Done, tests are fixed.

**Comment by gmoore** [comment]
Did this issue introduce any new variables?

**Comment by serge17** [comment]
@gmoore It added the option to select the build result. The readme and the jenkins wiki are already updated.

**Pull request merged**
