### PR TITLE
Int 321 include start date in security check

### PR DESCRIPTION
**Pull request by aliaandersen**
Include job start time in security check

### CODE REVIEW

**Review by bryanateoan — CHANGES_REQUESTED** [review]
- Update sdk version

Code looks good.

**Review by bryanateoan — CHANGES_REQUESTED** [review]
- Change SDK version to latest release 2.19

**Comment by aliaandersen** [comment]
?? The sdk was updated to 2.20: https://github.com/Contrast-Security-OSS/contrast-sdk-java/commit/4a751f0c44d5d5425bedd01b9e9f10835f2f77c7

**Comment by bryanateoan** [comment]
The latest release is 2.19 https://github.com/Contrast-Security-OSS/contrast-sdk-java/releases

**Review by bryanateoan — APPROVED** [review]

**Review by gmoore — APPROVED** [review]
Approved pending fixing the build.

**Pull request merged**
